// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpY1GtcsZtePV37oYowiZPv3LibL0v6Y8',
    appId: '1:547993200819:android:2c78d43bf4000a4ae5e8c6',
    messagingSenderId: '547993200819',
    projectId: 'zepwash-prod',
    storageBucket: 'zepwash-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDerteCHtmMg6Y7pVhPkVeXgMeiIH8RsdU',
    appId: '1:528614299140:ios:fbf499453685c3a35c4751',
    messagingSenderId: '528614299140',
    projectId: 'zepwashofficial-54555',
    storageBucket: 'zepwashofficial-54555.firebasestorage.app',
    iosBundleId: 'com.zepwash.zepwash',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQvd7ZJ2B0wu4jupTMe7NGyf29_gbCYs',
    appId: '1:547993200819:web:2ce4e82cf16018a9e5e8c6',
    messagingSenderId: '547993200819',
    projectId: 'zepwash-prod',
    authDomain: 'zepwash-prod.firebaseapp.com',
    storageBucket: 'zepwash-prod.firebasestorage.app',
    measurementId: 'G-9S1GPVEXWT',
  );

}